/* Generated By:JJTree: Do not edit this line. ASTArgList_Assign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgList_Assign extends SimpleNode {
  public ASTArgList_Assign(int id) {
    super(id);
  }

  public ASTArgList_Assign(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e868b966358c69c6f031d6cd51a77912 (do not edit this line) */
