/* Generated By:JJTree: Do not edit this line. ASTExpression_arith.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression_arith extends SimpleNode {
  public ASTExpression_arith(int id) {
    super(id);
  }

  public ASTExpression_arith(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a8a8deefc9bb3de69838f3cbdad3391c (do not edit this line) */
