/* Generated By:JJTree: Do not edit this line. ASTNemp_Param_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNemp_Param_List extends SimpleNode {
  public ASTNemp_Param_List(int id) {
    super(id);
  }

  public ASTNemp_Param_List(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1cdde09668e709c03fc99e824a591f49 (do not edit this line) */
