/* Generated By:JJTree: Do not edit this line. ASTnotEquals.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnotEquals extends SimpleNode {
  public ASTnotEquals(int id) {
    super(id);
  }

  public ASTnotEquals(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=894ab5c611377c0cb15dbdb0762a6da7 (do not edit this line) */
