/* Generated By:JavaCC: Do not edit this line. CCALTokeniserTreeConstants.java Version 6.0_1 */
public interface CCALTokeniserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTFUNCTION = 4;
  public int JJTRETURN = 5;
  public int JJTTYPE = 6;
  public int JJTPARAM_LIST = 7;
  public int JJTPARAMETERS = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTASSIGN = 11;
  public int JJTFUNCTIONCALL = 12;
  public int JJTPLUS = 13;
  public int JJTMINUS = 14;
  public int JJTAND = 15;
  public int JJTOR = 16;
  public int JJTCOMP = 17;
  public int JJTEQUALS = 18;
  public int JJTNOTEQUALS = 19;
  public int JJTLT = 20;
  public int JJTLE = 21;
  public int JJTGT = 22;
  public int JJTGE = 23;
  public int JJTID = 24;
  public int JJTNUMBER = 25;
  public int JJTBOOL = 26;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Var",
    "Const",
    "Function",
    "Return",
    "Type",
    "Param_list",
    "Parameters",
    "Main",
    "Statement",
    "Assign",
    "FunctionCall",
    "Plus",
    "Minus",
    "And",
    "Or",
    "Comp",
    "equals",
    "notEquals",
    "LT",
    "LE",
    "GT",
    "GE",
    "ID",
    "Number",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=05a5f0826c748b97b753e7ea3b874470 (do not edit this line) */
