/* Generated By:JavaCC: Do not edit this line. CCALTokeniserDefaultVisitor.java Version 6.0_1 */
public class CCALTokeniserDefaultVisitor implements CCALTokeniserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVar node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConst node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunction node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParam_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTParameters node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMain node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssign node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPlus node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMinus node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAnd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTComp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTequals node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnotEquals node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBool node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=2aa3fb37807bad308a3e644840afaafe (do not edit this line) */
