/* Generated By:JavaCC: Do not edit this line. CCALTokeniserVisitor.java Version 6.0_1 */
public interface CCALTokeniserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVar node, Object data);
  public Object visit(ASTConst node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTReturn node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTParam_list node, Object data);
  public Object visit(ASTParameters node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTAssign node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTPlus node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTComp node, Object data);
  public Object visit(ASTequals node, Object data);
  public Object visit(ASTnotEquals node, Object data);
  public Object visit(ASTLT node, Object data);
  public Object visit(ASTLE node, Object data);
  public Object visit(ASTGT node, Object data);
  public Object visit(ASTGE node, Object data);
  public Object visit(ASTID node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTBool node, Object data);
}
/* JavaCC - OriginalChecksum=9c20e71173e64f27d58ece5724b03562 (do not edit this line) */
